# Generated by Django 5.1.5 on 2025-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwaterintake',
            name='email_frequency',
            field=models.IntegerField(choices=[(1, 'Every 1 hour'), (2, 'Every 2 hour'), (4, 'Every 4 hour'), (6, 'Every 6 hour'), (12, 'Every 12 hour'), (24, 'Every one day')], default=1),
            preserve_default=False,
        ),
    ]
