# Generated by Django 5.1.5 on 2025-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0002_userwaterintake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwaterintake',
            name='session_key',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
