# Generated by Django 5.1.5 on 2025-03-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0002_userwaterintake_email_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savegoal',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='watertake',
            name='session_key',
        ),
    ]
