# Generated by Django 5.1.5 on 2025-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0003_rename_timestap_userwaterintake_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwaterintake',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userwaterintake',
            name='exercises_type',
            field=models.CharField(max_length=50),
        ),
    ]
