# Generated by Django 5.1.5 on 2025-02-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0004_userwaterintake_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwaterintake',
            name='exercises_type',
        ),
        migrations.RemoveField(
            model_name='userwaterintake',
            name='location',
        ),
    ]
