# Generated by Django 5.1.5 on 2025-02-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0005_remove_userwaterintake_exercises_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwaterintake',
            name='water_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
