# Generated by Django 5.1.5 on 2025-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0006_alter_userwaterintake_water_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwaterintake',
            name='part_water_in_day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
