# Generated by Django 5.1.5 on 2025-02-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0007_userwaterintake_part_water_in_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwaterintake',
            name='part_water_in_day',
        ),
    ]
