# Generated by Django 5.1.5 on 2025-02-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0008_remove_userwaterintake_part_water_in_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwaterintake',
            name='user',
        ),
    ]
